# Generated by Django 4.2.20 on 2025-08-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="diagnosis",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Диагноз"
            ),
        ),
    ]
