# Generated by Django 4.2.20 on 2025-08-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0002_diagnosis_diagnosis"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="distancnye_svistyashchie_hripi",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Дистантные свистящие хрипы"
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="krepitaciya",
            field=models.IntegerField(blank=True, null=True, verbose_name="Крепитация"),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="suhie_hripi",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Сухие хрипы"
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="vlazhnye_hripi",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Влажные хрипы"
            ),
        ),
    ]
