# Generated by Django 4.2.20 on 2025-08-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0003_diagnosis_distancnye_svistyashchie_hripi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="recomendation_healing",
            field=models.TextField(
                blank=True, null=True, verbose_name="Рекомендуемое лечение"
            ),
        ),
    ]
