# Generated by Django 4.2.20 on 2025-08-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0004_diagnosis_recomendation_healing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diagnosis",
            options={"verbose_name_plural": "Диагнозы"},
        ),
    ]
